Dat = Dict(
"Mag1" => "single",
"Mag2" => "single",
"Mag4" => "single",
"Ene1" => "single",
"Ene2" => "single",
"Ene4" => "single",
"Qvr1" => "single",
"Qvr2" => "single",
"Qvr4" => "single",
"Qnk1" => "single",
"Qnk2" => "single",
"Qnk4" => "single",
"R0tot"   => "single",
"R1tot"   => "single",
"R2tot"   => "single",
"R0max"   => "single",
"R1max"   => "single",
"R2max"   => "single",
"R0min"   => "single",
"R1min"   => "single",
"R2min"   => "single",
"Magcor" => "single",
"Magsid" => "single",
"Magbul" => "single",
"ChiM" => "complx",  #[<m^2>]-[<m>]^2
"BinM" => "complx",  #[<m^4>]/[<m^2>]^2
"AutM" => "complx",
"ChiE" => "complx",  #[<E^2>]-[<E>]^2
"BinE" => "complx",  #[<E^4>]/[<E^2>]^2
"AutE" => "complx",
"ChiQ" => "complx",  #[<q^2>]-[<q>]^2
"BinQ" => "complx",  #[<q^4>]/[<q^2>]^2
"AutQ" => "complx",
"ChiK" => "complx",  #[<K^2>]-[<K>]^2
"BinK" => "complx",  #[<K^2>-<K>^2]/[<K^2>]-[<K>]^2
"AutK" => "complx",
"AutO" => "complx",
"CtdE" => "complx",  #[<E^2>-<E>^2]
"CtdM" => "complx",  #[<M^2>-<M>^2]
"CtdQ" => "complx",  #[<q^2>-<q>^2]
"CtdK" => "complx",  #[<K^2>-<K>^2]
"BtdM" => "complx",  #[<m^4>/<m^2>^2]
"BtdQ" => "complx",  #[<q^4>/<q^2>^2]
"ChdM" => "complx",  #[<m^2>]-[<m>]    
"ChdQ" => "complx",  #[<q^2>]-[<q>] 
"QeaD" => "complx",  
"HwiD" => "complx",
"ChQQ" => "complx",  #[<q^4>]-[<q^2>]^2
"CtQQ" => "complx",  #[<q^4>-<q^2>^2]
"BiQQ" => "complx",  #[<q^4>-<q^2>^2]/[<q^4>]-[<q^2>]^2
)
